export const sampleO2C = {
  title: 'Order to Cash (O2C)',
  lanes: [
    { id: 'l1', name: 'Customer', color: 0 },
    { id: 'l2', name: 'Sales', color: 1 },
    { id: 'l3', name: 'Warehouse', color: 2 },
    { id: 'l4', name: 'Finance', color: 3 },
  ],
  steps: [
    { id: 's1', laneId: 'l1', label: 'Place Order', type: 'start', x: 80, y: 30, adoRef: '', description: '' },
    { id: 's2', laneId: 'l2', label: 'Review Order', type: 'process', x: 280, y: 30, adoRef: 'Feature-101', description: '' },
    { id: 's3', laneId: 'l4', label: 'Credit Check', type: 'decision', x: 480, y: 30, adoRef: 'Feature-102', description: '' },
    { id: 's4', laneId: 'l2', label: 'Confirm Order', type: 'process', x: 680, y: 30, adoRef: 'Feature-103', description: '' },
    { id: 's5', laneId: 'l2', label: 'Reject Order', type: 'end', x: 480, y: 30, adoRef: '', description: '' },
    { id: 's6', laneId: 'l3', label: 'Pick & Pack', type: 'process', x: 880, y: 30, adoRef: 'PBI-201', description: '' },
    { id: 's7', laneId: 'l3', label: 'Ship Goods', type: 'process', x: 1080, y: 30, adoRef: 'PBI-202', description: '' },
    { id: 's8', laneId: 'l4', label: 'Generate Invoice', type: 'process', x: 1080, y: 30, adoRef: 'Feature-104', description: '' },
    { id: 's9', laneId: 'l4', label: 'Payment Received?', type: 'decision', x: 1280, y: 30, adoRef: '', description: '' },
    { id: 's10', laneId: 'l4', label: 'Record Payment', type: 'process', x: 1480, y: 30, adoRef: 'PBI-301', description: '' },
    { id: 's11', laneId: 'l1', label: 'Order Complete', type: 'end', x: 1680, y: 30, adoRef: '', description: '' },
  ],
  connections: [
    { id: 'c1', from: 's1', to: 's2', label: '' },
    { id: 'c2', from: 's2', to: 's3', label: '' },
    { id: 'c3', from: 's3', to: 's4', label: 'Yes' },
    { id: 'c4', from: 's3', to: 's5', label: 'No' },
    { id: 'c5', from: 's4', to: 's6', label: '' },
    { id: 'c6', from: 's6', to: 's7', label: '' },
    { id: 'c7', from: 's7', to: 's8', label: '' },
    { id: 'c8', from: 's8', to: 's9', label: '' },
    { id: 'c9', from: 's9', to: 's10', label: 'Yes' },
    { id: 'c10', from: 's10', to: 's11', label: '' },
  ],
};
